# -*- coding: utf-8 -*-
"""pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEXfwExO2UtVjOro4Nx8cBu7X8E-uFSw
"""

# Right-angled triangle pattern
rows = 5
for i in range(1, rows + 1):
    print("*" * i)

# Inverted right-angled triangle pattern
rows = 5
for i in range(rows, 0, -1):
    print("*" * i)

# Pyramid pattern
rows = 5
for i in range(1, rows + 1):
    print(" " * (rows - i) + "*" * (2 * i - 1))

# Diamond pattern
rows = 5
# Upper part
for i in range(1, rows + 1):
    print(" " * (rows - i) + "*" * (2 * i - 1))
# Lower part
for i in range(rows - 1, 0, -1):
    print(" " * (rows - i) + "*" * (2 * i - 1))

# Number pyramid pattern
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

# Pascal's triangle
rows = 5
for i in range(rows):
    for j in range(rows - i):
        print(" ", end="")
    C = 1
    for j in range(1, i + 1):
        print(C, end=" ")
        C = C * (i - j) // j
    print()